######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 18:43:06 2016
######################################################################

TEMPLATE = app
TARGET = R3
INCLUDEPATH += .

# Input
HEADERS += library.h libraryui.h totalui.h
SOURCES += library.cpp libraryClient-v2.cpp libraryui.cpp totalui.cpp
