######################################################################
# Automatically generated by qmake (3.0) Thu Feb 18 21:59:55 2016
######################################################################

TEMPLATE = app
TARGET = Project2
INCLUDEPATH += .

# Input
HEADERS += film.h
SOURCES += film.cpp
