######################################################################
# Automatically generated by qmake (3.0) Fri Feb 19 16:26:17 2016
######################################################################

TEMPLATE = app
TARGET = Project2
INCLUDEPATH += .

# Input
HEADERS += educational.h entertainment.h film.h
SOURCES += educational.cpp entertainment.cpp film.cpp main.cpp
