######################################################################
# Automatically generated by qmake (3.0) Fri Feb 19 19:58:25 2016
######################################################################

TEMPLATE = app
TARGET = R1
INCLUDEPATH += .

# Input
HEADERS += educational.h entertainment.h film.h filmlist.h
SOURCES += educational.cpp entertainment.cpp film.cpp filmlist.cpp main.cpp
