######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 15:31:07 2016
######################################################################

TEMPLATE = app
TARGET = R2
INCLUDEPATH += .

# Input
HEADERS += library.h libraryui.h 
SOURCES += library.cpp \
           libraryClient-v2.cpp \
           libraryui.cpp \
